export enum ProductActionTypes {
  BEGIN_PRODUCTS_DOWNLOAD = '@@BEGIN_PRODUCTS_DOWNLOAD',
  PRODUCTS_DOWNLOAD_OK = '@@PRODUCTS_DOWNLOAD_OK',
  PRODUCTS_DOWNLOAD_ERROR = '@@PRODUCTS_DOWNLOAD_ERROR',

  ADD_PRODUCT = '@@ADD_PRODUCT',
  ADD_PRODUCT_OK = '@@ADD_PRODUCT_OK',
  ADD_PRODUCT_ERROR = '@@ADD_PRODUCT_ERROR',

  RETRIEVE_PRODUCT_EDIT = '@@RETRIEVE_PRODUCT_EDIT',
  BEGIN_EDIT_PRODUCT = '@@BEGIN_EDIT_PRODUCT',
  PRODUCT_EDITED_OK = '@@PRODUCT_EDITED_OK',
  PRODUCT_EDITED_ERROR = '@@PRODUCT_EDITED_ERROR',

  RETRIEVE_PRODUCT_DELETE = '@@RETRIEVE_PRODUCT_DELETE',
  PRODUCT_DELETED_OK = '@@PRODUCT_DELETED_OK',
  PRODUCT_DELETED_ERROR = '@@PRODUCT_DELETED_ERROR',

  //Alert
  SHOW_ALERT = '@@SHOW_ALERT',
  HIDE_ALERT = '@@HIDE_ALERT',
}
